name: Main

on: 
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:  
  hello-world:
    name: 'Print Hello World'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Echo
        run: |
          node -v